---
title: "gwas.ldsc_plot"
---

```{r knitr, include = FALSE}
DOCNAME <- "gwas.ldsc_plot"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Load libs

```{r}
library(tidyverse)

# plot
library(ggpubr)
library(scales)
library(scattermore)
library(ggrastr)
library(ggrepel)
library(ggVennDiagram)

# heatmap
library(ComplexHeatmap)
library(pheatmap)

# patch
library(patchwork)
library(cowplot)
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(viridis)
library(RColorBrewer)
library(ggsci)

# srat
#library(Seurat)

# set random seed for reproducibility
set.seed(12345)
```

```{r source, cache = FALSE}
source(here::here("utils/preprocess.R"))
#source(here::here("utils/markers.R"))
source(here::here("utils/plot.R"))
source(here::here("utils/gwas_enrichment.R"))
theme_set(publ_theme)
source("/work/DevM_analysis/utils/colors.R")
```

## Set up

```{r}
work_dir <- "/work/home/project/20231127_DevM/gwas"

celltype_order <- c("HSC", "GP", "Granulocyte",
                    "MEMP-t", "MEMP", "MEP", "MEMP-Mast-Ery", "MEMP-Ery", "Early-Ery", "Late-Ery",
                    "MEMP-MK", "MK", "MastP-t", "MastP", "Mast", "MDP",
                    "Monocyte", "Kupffer", "cDC1", "cDC2", "pDC", "ASDC",
                    "LMPP", "LP", "Cycling-LP", "PreProB", "ProB-1", "ProB-2",
                    "Large-PreB", "Small-PreB", "IM-B",
                    "NK", "ILCP", "T",
                    "Hepatocyte", "Endothelia")
```

## Blood cell traits

Blood cell traits

```{r}
df_bct <- read_csv(file.path(work_dir, "gwas_traits.h2_z-score.csv")) |> 
  filter(study %in% c("32888494")) |>  # only blood cell traits
  filter(heritability_z > 4) |> 
  mutate(type = factor(type, levels = c("WBC-Lymp", "Phil", "RBC", "PLT")),
         pheno = factor(pheno)) |> 
  arrange(type, pheno) |> 
  as.data.frame()
rownames(df_bct) <- df_bct$pheno

dim(df_bct)
table(df_bct$type)
```

FDR5 & LFC1

```{r}
result_dir <- file.path(work_dir, "sLDSC/ldsc_h2-cts_bigCTRL/FDR5_LFC1_padding_1k")

# No. peak < 3000
to_exclude <- c("MEMP", "MastP-t", "MDP")

df_res_bct <- read_h2_cts_results(df_bct$pheno, result_dir, exclude_cells = to_exclude) |>
  mutate(
    Name = factor(Name, levels = celltype_order),
    trait = factor(trait, levels = df_bct$pheno)
  )
```

```{r fig.width=7, fig.height=9}
plot_ldsc_pheatmap(
  dat = df_res_bct, plot_value = "log_p", display_sig = TRUE, maxSig = 10, anno_df = df_bct,
  cluster_rows = FALSE, cluster_cols = FALSE, labels_col = df_bct$pheno_label
)

pdf(file = here::here("output", DOCNAME, "gwas.ldsc_blood_cell_traits.pdf"),
    width = 7, height = 9)
plot_ldsc_pheatmap(
  dat = df_res_bct, plot_value = "log_p", display_sig = TRUE, maxSig = 10, anno_df = df_bct,
  cluster_rows = FALSE, cluster_cols = FALSE, labels_col = df_bct$pheno_label
)
invisible(dev.off())
```

```{r fig.width=7, fig.height=9}
plot_ldsc_pheatmap(
  dat = df_res_bct, plot_value = "log_p", display_sig = FALSE, maxSig = 10, anno_df = df_bct,
  cluster_rows = FALSE, cluster_cols = FALSE, labels_col = df_bct$pheno_label, treeheight_row = 0,
)
```

## Disease traits (heritability_z > 4)

```{r}
df_traits <- read_csv(file.path(work_dir, "gwas_traits.h2_z-score.csv")) |> 
  filter(study %ni% c("35007327", "32888494", "38116119")) |>  # no blood cell traits, no biomarker
  filter(heritability_z > 4) |> 
  mutate(type = factor(type, levels = c("Blood cancer", "Blood disease", "Immune", "Solid cancer", "Other")),
         pheno = factor(pheno)) |> 
  arrange(type, pheno) |> 
  as.data.frame()
rownames(df_traits) <- df_traits$pheno

dim(df_traits)
table(df_traits$type)
```

plot

```{r}
result_dir <- file.path(work_dir, "sLDSC/ldsc_h2-cts_bigCTRL/FDR5_LFC1_padding_1k")

# No. peak < 3000
to_exclude <- c("MEMP", "MastP-t", "MDP")

df_res_d <- read_h2_cts_results(df_traits$pheno, result_dir, exclude_cells = to_exclude) |>
  mutate(
    Name = factor(Name, levels = celltype_order),
    trait = factor(trait, levels = df_traits$pheno)
  )
```

```{r fig.width=9, fig.height=8}
plot_ldsc_pheatmap(
  dat = df_res_d, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE,
  anno_df = df_traits,
  keep_sig_col = FALSE, keep_sig_row = FALSE)
```

```{r fig.width=9, fig.height=8}
plot_ldsc_pheatmap(
  dat = df_res_d, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE,
  anno_df = df_traits,
  keep_sig_col = FALSE, keep_sig_row = FALSE,
  labels_col = df_traits$pheno_label)
```

## Disease traits (finalize)

```{r}
df_traits2 <- df_traits |> 
  filter(pheno != "ra_Shirai") |> # lower heritability_z than the other two
  filter(pheno != "ms_GCST005531") |> # much lower sample size than the other one
  filter(pheno != "covid_A2") |>  # covid_B2 is enough
  droplevels() |> 
  as.data.frame()
rownames(df_traits2) <- df_traits2$pheno
dim(df_traits2)

result_dir <- file.path(work_dir, "sLDSC/ldsc_h2-cts_bigCTRL/FDR5_LFC1_padding_1k")

# No. peak < 3000
to_exclude <- c("MEMP", "MastP-t", "MDP")

df_res_d2 <- read_h2_cts_results(df_traits2$pheno, result_dir, exclude_cells = to_exclude) |>
  mutate(
    Name = factor(Name, levels = celltype_order),
    trait = factor(trait, levels = df_traits2$pheno)
  )
```

No clustering

```{r fig.width=9, fig.height=8}
plot_ldsc_pheatmap(
  dat = df_res_d2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE,
  anno_df = df_traits2,
  keep_sig_col = FALSE, keep_sig_row = FALSE)
```

```{r fig.width=8.5, fig.height=8.5}
plot_ldsc_pheatmap(
  dat = df_res_d2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE,
  anno_df = df_traits2,
  keep_sig_col = FALSE, keep_sig_row = FALSE,
  labels_col = df_traits2$pheno_label)

pdf(file = here::here("output", DOCNAME, "gwas.ldsc_disease_traits.pdf"),
    width = 8.5, height = 8.5)
plot_ldsc_pheatmap(
  dat = df_res_d2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE,
  anno_df = df_traits2,
  keep_sig_col = FALSE, keep_sig_row = FALSE,
  labels_col = df_traits2$pheno_label)
invisible(dev.off())
```

Clustering

```{r fig.width=9, fig.height=8}
plot_ldsc_pheatmap(
  dat = df_res_d2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = TRUE,
  anno_df = df_traits2,
  keep_sig_col = FALSE, keep_sig_row = FALSE)
```

```{r fig.width=9, fig.height=9}
plot_ldsc_pheatmap(
  dat = df_res_d2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = TRUE,
  anno_df = df_traits2,
  keep_sig_col = FALSE, keep_sig_row = FALSE,
  labels_col = df_traits2$pheno_label)
```

Only show sig. ones (no endothelia)

```{r fig.width=4, fig.height=4}
df2 <- df_res_d2 |> 
  filter(Name != "Endothelia") |> 
  droplevels()

plot_ldsc_pheatmap(
  dat = df2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE,
  keep_sig_col = TRUE, keep_sig_row = TRUE)
```

```{r fig.width=4, fig.height=4.5}
plot_ldsc_pheatmap(
  dat = df2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE, keep_sig_col = TRUE, keep_sig_row = TRUE,
  labels_col = df_traits2$pheno_label)

pdf(file = here::here("output", DOCNAME, "gwas.ldsc_disease_traits.only_sig.pdf"),
    width = 4, height = 4.5)
plot_ldsc_pheatmap(
  dat = df2, plot_value = "log_p", display_sig = TRUE, maxSig = 100,
  cluster_rows = FALSE, cluster_cols = FALSE, keep_sig_col = TRUE, keep_sig_row = TRUE,
  labels_col = df_traits2$pheno_label)
invisible(dev.off())
```

## Save

Trait

```{r}
df_bct$type <- "Blood cell"
df_trait_final <- rbind(df_bct, df_traits2) |> 
  dplyr::select(study, category = type, trait = pheno_label, n_sample, heritability_z)
rownames(df_trait_final) <- NULL
DT::datatable(df_trait_final)

df_trait_final |> 
  write_csv(file = here::here("output", DOCNAME, "gwas.traits_used.csv"))
```

sLDSC

```{r}
tmp_df <- rbind(df_bct, df_traits2) |> 
  dplyr::select(trait = pheno, pheno_label, type)

df_ldsc_final <- rbind(df_res_bct, df_res_d2) |> 
  left_join(tmp_df, by = "trait") |> 
  dplyr::select(celltype = Name, trait = pheno_label,
                category = type, 
                coefficient_p = Coefficient_P_value,
                coefficient_p_bh = FDR_BH) |> 
  arrange(category, coefficient_p)

df_ldsc_final |> 
  write_csv(file = here::here("output", DOCNAME, "gwas.sLDSC_result.csv"))
```

```{r}
df_ldsc_final |> 
  filter(coefficient_p < 0.05) |> 
  DT::datatable()
```

## Session info
