---
title: "HSC.lmmPG_plot"
---

```{r knitr, include = FALSE}
DOCNAME <- "HSC.lmmPG"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Set up

```{r}
library(tidyverse)

# plot
library(scales)
library(scattermore)
library(ggrastr)
library(ggpubr)

# heatmap
library(ComplexHeatmap)
library(pheatmap)

# patch
library(patchwork)
library(cowplot)
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(RColorBrewer)
library(ggsci)

# srat
library(Seurat)

# set random seed for reproducibility
set.seed(12345)
```

```{r source, cache = FALSE}
source(here::here("utils/preprocess.R"))
#source(here::here("utils/markers.R"))
source(here::here("utils/plot.R"))
theme_set(publ_theme)
source("/work/DevM_analysis/utils/colors.R")
```

## Load data

srat

```{r}
srat <- readRDS("/work/DevM_analysis/01.annotation/11.subclustering/HSC/data/FL_rna_clustered.v01.rds")
srat
```

PG

```{r}
df_pg <- readRDS(here::here("output", "HSC.lmmPG", "HSC.lmmPG_FDR20.rds"))
dim(df_pg)
numEnhancerPerGene <- readRDS(here::here("output", "HSC.lmmPG", "HSC.lmmPG_FDR20.numEnhancerPerGene.rds"))
```

PG anno with DE and DA

```{r}
df_anno_de_da <- readRDS(here::here("output", "HSC.lmmPG", "HSC.lmmPG_FDR20.anno_de_da.rds"))
```

## Plot

no. of enhancers vs. gene exp.

```{r fig.width=3, fig.height=3}
exp <- AverageExpression(srat, features = intersect(unique(df_pg$gene), rownames(srat)), group.by = "celltype")$RNA |>
  as.data.frame() |>
  rownames_to_column("gene") |>
  dplyr::select(gene, exprs = all)

p1 <- numEnhancerPerGene |>
  left_join(exp, by = c("gene" = "gene")) |>
  filter(!is.na(exprs)) |> 
  ggplot(aes(x = REnum, y = exprs)) +
  geom_boxplot(outliers = F) +
  labs(
    x = "Enhancer number", y = "Gene expression"
  ) +
  publ_theme
p1
```

Congruence with DE/DA?

```{r fig.width=3, fig.height=3}
p2 <- df_anno_de_da |> 
  ggplot(aes(x = peak_dev_da_beta, y = gene_dev_de_beta)) +
  geom_scattermore(pointsize = 2) +
  #guides(colour = guide_legend(override.aes = list(size=5))) +
  stat_cor(aes(group = 1)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "HSC dev da: LMM beta for peak", y = "HSC dev de: LMM beta for gene") +
  publ_theme
p2
```

Align

```{r fig.width=6, fig.height=3}
p1 + p2

ggsave2(
  filename = here::here("output", DOCNAME, "HSC.lmmPG_plot.pdf"),
  width = 6, height = 3
)
```

## Session info

