---
title: "HSC.dev_de_plot"
---

```{r knitr, include = FALSE}
DOCNAME <- "HSC.dev_de_plot"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Set up

```{r}
library(tidyverse)

# plot
library(ggpubr)
library(scales)
library(scattermore)
library(ggrastr)
library(ggrepel)

# heatmap
library(ComplexHeatmap)
library(pheatmap)

# patch
library(patchwork)
library(cowplot)
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(RColorBrewer)
library(ggsci)

# srat
library(Seurat)

# ORA
library(clusterProfiler)

# set random seed for reproducibility
set.seed(12345)
```

```{r source, cache = FALSE}
source(here::here("utils/preprocess.R"))
#source(here::here("utils/markers.R"))
source(here::here("utils/plot.R"))
theme_set(publ_theme)
source("/work/DevM_analysis/utils/colors.R")
```

## Load data

Load

```{r}
mdata <- readRDS(here::here("output", "HSC.dev_de_lmm", "mdata.rds"))
srat <- readRDS("/work/DevM_analysis/02.abundance/Milo_FL_HSC_PCW250401/data/FL_rna_clustered.rds")
table(srat$PCW, useNA = "ifany")
```

LMM res.

```{r}
df_de <- readRDS(here::here("output", "HSC.dev_de_lmm", "HSC_lmm_de_time_df.rds"))
df_de_sig <- df_de[df_de$ltsr > 0.9,]

deg_lst <- list(
  LMM_up = df_de |> filter(ltsr > 0.9, beta > 0) |> pull(gene),
  LMM_dn = df_de |> filter(ltsr > 0.9, beta < 0) |> pull(gene)
)
```

## DE Heatmap {.tabset}

### in one

Genes selected by Ana: <https://sanger-cvejic-group.slack.com/archives/C07JEUB723F/p1747744105361549>

```{r fig.width=5, fig.height=6}
# beta
mat <- as.matrix(df_de_sig[,"beta"])
colnames(mat)[1] <- "beta"
rownames(mat) <- df_de_sig$gene

# color for mat
#range(mat[,1])
#quantile(mat[,1], c(0.01, 0.05, 0.1, 0.5, 0.8, 0.9, 0.95, 0.99), na.rm=TRUE)
col_fun = circlize::colorRamp2(c(-0.4, 0, 0.4), c("blue", "white", "red"))

# genes to highlight
gene_df <- data.frame(
  gene = c("HLF", "PRDM16", "MLLT3", "PROM1",
            "FLT3", "KLF6", "KIT",
            "HLA-DRB1", "HLA-DRA",
            "BCR", "SGIP1", "CD300LF",
            "TGFBR2", "SMAD3",
            "HSPA4L", "HSPA4", "AGR2",
            "COX4I1", "COX6B1",
            "NDUFB5", "NDUFB9"),
  gene_group = c(rep("HSC genes", 4),
                 rep("B cell differentiation", 3),
                 rep("MHC class II protein complex assembly", 2),
                 rep("Positive regulation of endocytosis", 3),
                 rep("TGF-beta receptor signalling", 2),
                 rep("Response to unfolded protein", 3),
                 rep("Oxidative phosphorylation", 2),
                 rep("ATP synthesis coupled electron transport", 2)
                 )
)
gene_df$gene_group <- factor(gene_df$gene_group, levels = c("HSC genes", "B cell differentiation",
                                                            "MHC class II protein complex assembly",
                                                            "Positive regulation of endocytosis",
                                                            "TGF-beta receptor signalling",
                                                            "Response to unfolded protein",
                                                            "Oxidative phosphorylation",
                                                            "ATP synthesis coupled electron transport"))
# gene group colors
gene_group_levels <- levels(gene_df$gene_group)
# RColorBrewer
#group_colors <- setNames(brewer.pal(length(gene_group_levels), "Set2"), gene_group_levels)
# ggsci
group_colors <- setNames(pal_nejm()(length(gene_group_levels)), gene_group_levels)
gene_df$gene_color <- group_colors[as.character(gene_df$gene_group)]

# label location
gth = sapply(gene_df$gene, function(x){which(rownames(mat) == x)}, simplify = T)

# rowname anno
ha = rowAnnotation(foo = anno_mark(at = gth, labels = names(gth),
                                   labels_gp = gpar(fontsize = 10,
                                                    col = gene_df$gene_color,
                                                    fontface = "bold"),
                                   link_gp = gpar(col = gene_df$gene_color)))

# legend for gene groups
gene_group_legend <- Legend(
  title = "Group",
  labels = names(group_colors),
  legend_gp = gpar(fill = group_colors),
  labels_gp = gpar(fontsize = 10),
  title_gp = gpar(fontsize = 10),
  #column_gap = unit(2, "mm"),
  row_gap = unit(2, "mm")
)
pd = packLegend(gene_group_legend, max_width = unit(5.5, "cm"))

ht = Heatmap(mat, name = "beta",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        show_column_names = FALSE,
        #column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    title_position = "topcenter",
                                    grid_height = unit(1.5, "mm"),
                                    grid_width = unit(1.5, "mm")),
        width = unit(0.5, "cm")
        )
#draw(ht, heatmap_legend_side = "bottom")
p.ht = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "top", annotation_legend_list = list(pd))))
p.ht

ggsave2(
  filename = here::here("output", DOCNAME, "HSC.dev_de_plot.beta_heatmap.pdf"),
  width = 5, height = 6
)
```

### MHC-II

```{r fig.width=1.5, fig.height=6}
mhc2 <- c("HLA-DRA", "HLA-DRB1", "HLA-DRB3", "HLA-DRB4", "HLA-DRB5",
          "HLA-DPA1", "HLA-DPB1", "HLA-DQA1", "HLA-DQA2",
          "HLA-DQB1", "HLA-DQB2", "HLA-DQB3",
          "HLA-DMA", "HLA-DMB", "HLA-DOA", "HLA-DOB",
          "CD74", "CIITA")

# label location
gth = sapply(intersect(mhc2, rownames(mat)), function(x){which(rownames(mat) == x)}, simplify = T)

# rowname anno
ha = rowAnnotation(foo = anno_mark(at = gth, labels = names(gth),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat, name = "beta",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        show_column_names = FALSE,
        heatmap_legend_param = list(direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    title_position = "topcenter",
                                    grid_height = unit(1.5, "mm"),
                                    grid_width = unit(1.5, "mm")),
        width = unit(0.5, "cm")
        )
#draw(ht, heatmap_legend_side = "bottom")
p.ht_mhc2 = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "top")))
p.ht_mhc2

ggsave2(
  filename = here::here("output", DOCNAME, "HSC.dev_de_plot.beta_heatmap.MHC-II.pdf"),
  width = 1.5, height = 6
)
```

### cell-cycle

```{r fig.width=1.5, fig.height=6}
cc_genes <- unlist(cc.genes.updated.2019)

# label location
gth = sapply(intersect(cc_genes, rownames(mat)), function(x){which(rownames(mat) == x)}, simplify = T)

# rowname anno
ha = rowAnnotation(foo = anno_mark(at = gth, labels = names(gth),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat, name = "beta",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        show_column_names = FALSE,
        heatmap_legend_param = list(direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    title_position = "topcenter",
                                    grid_height = unit(1.5, "mm"),
                                    grid_width = unit(1.5, "mm")),
        width = unit(0.5, "cm")
        )
#draw(ht, heatmap_legend_side = "bottom")
p.ht_cc = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "top")))
p.ht_cc

ggsave2(
  filename = here::here("output", DOCNAME, "HSC.dev_de_plot.beta_heatmap.cell-cycle.pdf"),
  width = 1.5, height = 6
)
```

### ATPase

```{r fig.width=5, fig.height=6}
# genes to highlight
gene_df <- data.frame(
  gene = c("NKAIN2",
           "ATP2C1", "ATP2B1", "ATP8B4", "ATP9A", "ATP10D",
            "ATP6V1A", "ATP6V1B2",
            "MT-ATP6", "ATP5PD", "ATP5PO", "ATP5MG", "ATP5ME",
           "ATP5MF", "ATP5MD", "ATP5MPL", "ATP5F1A", "ATP5F1B",
           "ATP5F1E", "ATP5PB", "ATP5PF", "ATP5MC1", "ATP5MC3"),
  gene_group = c(rep("P-type ATPase Interacting", 1),
                 rep("P-type ATPase", 5),
                 rep("V-type ATPase", 2),
                 rep("F-type ATPase", 15)
                 )
)
gene_df$gene_group <- factor(gene_df$gene_group, levels = c("P-type ATPase Interacting",
                                                            "P-type ATPase", "V-type ATPase",
                                                            "F-type ATPase"))
# gene group colors
gene_group_levels <- levels(gene_df$gene_group)
# RColorBrewer
#group_colors <- setNames(brewer.pal(length(gene_group_levels), "Set2"), gene_group_levels)
# ggsci
group_colors <- setNames(pal_nejm()(length(gene_group_levels)), gene_group_levels)
gene_df$gene_color <- group_colors[as.character(gene_df$gene_group)]

# label location
gth = sapply(gene_df$gene, function(x){which(rownames(mat) == x)}, simplify = T)

# rowname anno
ha = rowAnnotation(foo = anno_mark(at = gth, labels = names(gth),
                                   labels_gp = gpar(fontsize = 10,
                                                    col = gene_df$gene_color,
                                                    fontface = "bold"),
                                   link_gp = gpar(col = gene_df$gene_color)))

# legend for gene groups
gene_group_legend <- Legend(
  title = "Group",
  labels = names(group_colors),
  legend_gp = gpar(fill = group_colors),
  labels_gp = gpar(fontsize = 10),
  title_gp = gpar(fontsize = 10),
  #column_gap = unit(2, "mm"),
  row_gap = unit(2, "mm")
)
pd = packLegend(gene_group_legend, max_width = unit(5.5, "cm"))

ht = Heatmap(mat, name = "beta",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        show_column_names = FALSE,
        #column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    title_position = "topcenter",
                                    grid_height = unit(1.5, "mm"),
                                    grid_width = unit(1.5, "mm")),
        width = unit(0.5, "cm")
        )
#draw(ht, heatmap_legend_side = "bottom")
p.ht = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "top", annotation_legend_list = list(pd))))
p.ht
```

## Dotplot {.tabset}

### MHC-II

```{r fig.width=5, fig.height=3}
mhc2 <- filter_features(srat, mhc2)
mhc2

p <- DotPlot(srat, features = rev(mhc2), group.by = "PCW", scale = TRUE) +
  coord_flip() +
  labs(x = NULL, y = "PCW", title = "MHC-II exp. in FL HSC")

# Extract plot data
plot_data <- p$data

plot_data <- plot_data |> 
  mutate(features.group = case_when(
    features.plot %in% deg_lst$LMM_up ~ "Up",
    features.plot %in% deg_lst$LMM_dn ~ "Dn",
    TRUE ~ "NotSig"
))

# Define colors for each group
group_colors <- c("Up" = "red", "Dn" = "blue", "NotSig" = "gray")
gene_color_vector <- setNames(group_colors[plot_data$features.group], plot_data$features.plot)

p <- p +
  publ_theme +
  theme(axis.text.y = element_text(colour = gene_color_vector[levels(plot_data$features.plot)],
                                   face = "bold"))
p
```

add a gene group legend

```{r fig.width=5, fig.height=3}
# gene group legend
gene_group_legend <- Legend(
  title = "Group",
  labels = names(group_colors),
  legend_gp = gpar(fill = group_colors),
  labels_gp = gpar(fontsize = 6),
  title_gp = gpar(fontsize = 8),
  title_position = "topleft",
  row_gap = unit(2, "mm"),
  #direction = "horizontal", nrow = 1
)
pd = packLegend(gene_group_legend)
gl <- plot_grid(grid.grabExpr(draw(pd)))

p.dot_mhc2 <- gl + p +
  plot_layout(widths = c(0.2, 1))
p.dot_mhc2

ggsave2(
  filename = here::here("output", DOCNAME, "HSC.dev_de_plot.MHCII_dotplot.pdf"),
  width = 5, height = 3
)
```

### ATPase

also include CB and BM

```{r}
srat_hsc2 <- readRDS(here::here("output", "HSC.dev_de_MHCII", "HSC_FL_CB_BM.rds"))
```

```{r fig.width=8, fig.height=6}
atp_gene <- filter_features(srat_hsc2, gene_df$gene)
atp_gene

p <- DotPlot(srat_hsc2, features = rev(atp_gene), group.by = "PCW", scale = TRUE) +
  coord_flip() +
  labs(x = NULL, y = NULL, title = "ATPase (HSC in FL/CB/BM)")

# Extract plot data
plot_data <- p$data

plot_data <- plot_data |> 
  mutate(features.group = case_when(
    features.plot %in% deg_lst$LMM_up ~ "Up",
    features.plot %in% deg_lst$LMM_dn ~ "Dn",
    TRUE ~ "NotSig"
  ))

# Define colors for each group
group_colors <- c("Up" = "red", "Dn" = "blue", "NotSig" = "gray")
gene_color_vector <- setNames(group_colors[plot_data$features.group], plot_data$features.plot)

p +
  theme(axis.text.y = element_text(colour = gene_color_vector[levels(plot_data$features.plot)],
                                   face = "bold"))
```

## ORA

```{r}
cg.BP <- readRDS(here::here("output", "HSC.dev_de_lmm", "HSC_lmm_de_time.ORA_GOBP.rds"))
cg.MF <- readRDS(here::here("output", "HSC.dev_de_lmm", "HSC_lmm_de_time.ORA_GOMF.rds"))
cg.CC <- readRDS(here::here("output", "HSC.dev_de_lmm", "HSC_lmm_de_time.ORA_GOCC.rds"))

df_lst <- list(
  df1 <- cg.BP@compareClusterResult |> 
    mutate(group = "GO-BP") |>
    dplyr::select(Cluster, group, ID, Description, p.adjust),
  df2 <- cg.MF@compareClusterResult |> 
    mutate(group = "GO-MF") |>
    dplyr::select(Cluster, group, ID, Description, p.adjust),
  df3 <- cg.CC@compareClusterResult |> 
    mutate(group = "GO-CC") |>
    dplyr::select(Cluster, group, ID, Description, p.adjust)
)
df_ora <- do.call(rbind, df_lst) |> 
  mutate(group = factor(group, levels = c("GO-BP", "GO-MF", "GO-CC")))
```

test

```{r fig.width=8, fig.height=5}
# highlight
hlt_id <- c(
  # BP
  "GO:0045785", "GO:0002399", "GO:0007179", "GO:0030522", "GO:0045807", "GO:0030183",
  "GO:0006119",
  # MF
  "GO:0035259",
  "GO:0051082"
  # CC
)
df_hlt <- df_ora |> 
  filter(ID %in% hlt_id)

df_ora |> 
  ggplot(aes(x = group, y = -log10(p.adjust), color = group)) +
  geom_jitter(width = .2) +
  geom_text_repel(data = df_hlt, mapping = aes(x = group, y = -log10(p.adjust), label = Description),
                  min.segment.length = 0,
                  inherit.aes = FALSE) +
  labs(x = NULL, y = "-log10(p.adjust)") +
  facet_wrap(.~Cluster, scales = "free_y") +
  theme(legend.position = "none")
```

dotplot, simiplified GO-BP

```{r fig.width=3, fig.height=6}
s_cg.BP <- simplify(cg.BP, cutoff = 0.5)
p <- dotplot(s_cg.BP, showCategory = 10) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 40), position = "right") +
  scale_x_discrete(labels = c("Up-regulated", "Down-regulated")) +
  labs(x = NULL) +
  publ_theme +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.line = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, size = .5))
p

ggsave2(
  filename = here::here("output", DOCNAME, "HSC.dev_de_plot.ORA_GO-BP.pdf"),
  width = 3, height = 6
)
```

## Session info

