---
title: "HSC.dev_da_mcScale"
---

- Run `HSC.dev_da_mcScale.R` first

```{r knitr, include = FALSE}
DOCNAME <- "HSC.dev_da_mcScale"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Set up

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)

# plot
library(ggsci)
library(RColorBrewer)
library(scales)
library(ComplexHeatmap)
library(pheatmap)
library(scattermore)
library(ggrastr)
library(ggrepel)
library(ggpubr)
library(patchwork)
library(cowplot)
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# specific
library(Seurat)

# TF
library(monaLisa)
library(SummarizedExperiment)
library(BSgenome.Hsapiens.UCSC.hg38)

# ORA
library(ggVennDiagram)
library(ChIPseeker)
library(clusterProfiler)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- loadDb(here::here("data/cellranger-2020-A-2.0.0.txdb"))

# set random seed for reproducibility
set.seed(12345)
```

```{r source, cache = FALSE}
#source(here::here("utils/preprocess.R"))
source(here::here("utils/markers.R"))
source(here::here("utils/plot.R"))
theme_set(publ_theme)
source("/work/DevM_analysis/utils/colors.R")
```

## DA peak detection

DA res dir

```{r}
da_res_dir <- "HSC.dev_da_lmm_mc_scale"
```

LMM

```{r}
df_de_ln <- readRDS(here::here("output", da_res_dir, "HSC_dev_da_lmm_df.rds"))
df_de_ln <- df_de_ln[df_de_ln$ltsr > 0.9,]
table(ifelse(df_de_ln$beta > 0, "up", "dn"))
```

All peak anno

```{r, eval=FALSE}
peak_all <- readPeakFile(here::here("output", da_res_dir, "HSC_dev_da_lmm.peak_tested.bed"))
peakAnnoAll <- annotatePeak(peak_all,
                            level = "gene",
                            TxDb=txdb, tssRegion=c(-1000, 1000),
                            annoDb="org.Hs.eg.db", flankDistance = 1000, addFlankGeneInfo=T,
                            verbose=FALSE)
# save
saveRDS(peakAnnoAll,
        file = here::here("output", DOCNAME, "HSC_dev_da.peak_all_anno.rds"))
write_tsv(data.frame(peakAnnoAll@anno),
          file = here::here("output", DOCNAME, "HSC_dev_da.peak_all_anno.tsv"))
```

```{r}
peak_all <- readPeakFile(here::here("output", da_res_dir, "HSC_dev_da_lmm.peak_tested.bed"))
peakAnnoAll <- readRDS(here::here("output", DOCNAME, "HSC_dev_da.peak_all_anno.rds"))

#peak_seq <- getSeq(BSgenome.Hsapiens.UCSC.hg38, peak_all)
```

## DA peak Anno

da peaks

```{r , eval=FALSE}
peak_files = list(
  peak_up = here::here("output", da_res_dir, "HSC_dev_da_lmm.peak_up.bed"),
  peak_dn = here::here("output", da_res_dir, "HSC_dev_da_lmm.peak_dn.bed")
)

peakList = lapply(peak_files, readPeakFile)
peakAnnoList <- lapply(peakList, annotatePeak, level = "gene", TxDb=txdb, tssRegion=c(-1000, 1000),
                       annoDb="org.Hs.eg.db", flankDistance = 1000, addFlankGeneInfo=T,
                       verbose=FALSE)
# save
saveRDS(peakAnnoList, file = here::here("output", DOCNAME, "HSC_dev_da.peak_da_anno.rds"))
write_tsv(data.frame(peakAnnoList$peak_up@anno),
          file = here::here("output", DOCNAME, "HSC_dev_da.peak_up_anno.tsv"))
write_tsv(data.frame(peakAnnoList$peak_dn@anno),
          file = here::here("output", DOCNAME, "HSC_dev_da.peak_dn_anno.tsv"))
```

```{r}
peak_files = list(
  peak_up = here::here("output", da_res_dir, "HSC_dev_da_lmm.peak_up.bed"),
  peak_dn = here::here("output", da_res_dir, "HSC_dev_da_lmm.peak_dn.bed")
)

peakList = lapply(peak_files, readPeakFile)
peakAnnoList = readRDS(here::here("output", DOCNAME, "HSC_dev_da.peak_da_anno.rds"))
```

Compare annotations

```{r, fig.height=4, fig.width=6}
#up
plotAnnoPie(peakAnnoList[[1]])
```

```{r, fig.height=4, fig.width=6}
# dn
plotAnnoPie(peakAnnoList[[2]])
```

```{r, fig.height=3, fig.width=8}
plotAnnoBar(peakAnnoList) +
  theme_cowplot()
```

To TSS

```{r, fig.width=6, fig.height=3}
plotDistToTSS(peakAnnoList,
              title="Distribution of DA peaks\nrelative to TSS",
              ylab = "HSC peaks (%)") +
  theme_cowplot()
```

```{r, fig.width=12, fig.height=5}
p1 <- plotAvgProf2(peak_files[[1]], TxDb=txdb, upstream=3000, downstream=3000, conf = 0.95,
                  xlab="Genomic Region (5'->3')", ylab = "Peak Count Frequency") +
  labs(title = "DA peak-up")
p2 <- plotAvgProf2(peak_files[[2]], TxDb=txdb, upstream=3000, downstream=3000, conf = 0.95,
                  xlab="Genomic Region (5'->3')", ylab = "Peak Count Frequency") +
  labs(title = "DA peak-dn")
p1 + p2
```

## Heatmap {.tabset}

### HSC genes and HLA

Plot heatmap, marker HSC genes and HLA

```{r fig.width=1.5, fig.height=6}
# beta
da_atac_pro_sig <- da_atac_pro_sig |> filter(!is.na(gene))
mat <- as.matrix(da_atac_pro_sig[,"beta_atac"])
colnames(mat)[1] <- "beta"
rownames(mat) <- da_atac_pro_sig$gene

# color
#range(range(mat[,1]))
col_fun = circlize::colorRamp2(c(-0.4, 0, 0.4), c("blue", "white", "red"))

# label location
marker_2_lab <- intersect(rownames(mat), c(Hanna_HSC_signature, Hanna_HSC_TFs, grep("HLA|CIITA", rownames(mat), value = T)))
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(mat) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat, name = "beta",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(#direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p.beta = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.beta
```

### cell cycle

Plot heatmap, marker cell cycle genes

```{r fig.width=1.5, fig.height=6}
# label location
marker_2_lab <- intersect(rownames(mat), c(cc.genes.updated.2019$s.genes, cc.genes.updated.2019$g2m.genes))
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(mat) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat, name = "beta",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(#direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
p.beta = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.beta
```

## Peak anno by PG links {.tabset}

HSC PG links

```{r}
df_pg <- readRDS(here::here("output", "HSC.lmmPG", "HSC.lmmPG_FDR20.rds")) |> 
  dplyr::select(peak, gene)
dim(df_pg)
head(df_pg[,1:2])
```

Neat

```{r}
df <- df_de_ln |> 
  dplyr::rename(peak = gene) |> 
  left_join(df_pg, by = "peak") |> 
  filter(!is.na(gene))

dim(df)
head(df)
```

```{r eval=FALSE}
compareList <- list(
  peak_up = df |> 
    filter(beta > 0) |> 
    pull(gene) |> unique() |> 
    bitr(fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db") |> 
    pull(ENTREZID),
  peak_dn = df |> 
    filter(beta < 0) |> 
    pull(gene) |> unique() |> 
    bitr(fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db") |> 
    pull(ENTREZID)
)
# remove genes showed up in both
common_genes <- intersect(compareList$peak_up, compareList$peak_dn)
cmpList <- list(
  peak_up = setdiff(compareList$peak_up, common_genes),
  peak_dn = setdiff(compareList$peak_dn, common_genes)
)
lengths(cmpList)
# up: 744
# dn: 574

# ORA, KEGG
ck = compareCluster(cmpList, fun = "enrichKEGG", organism = "hsa", pvalueCutoff = 0.05)
ck <- setReadable(ck, 'org.Hs.eg.db', keyType = "ENTREZID")
saveRDS(ck, file = here::here("output", DOCNAME, "HSC_lmm_da_time.ORA_KEGG_by_PG.rds"))
as.data.frame(ck) |> 
  write_tsv(here::here("output", DOCNAME, "HSC_lmm_da_time.ORA_KEGG_by_PG.tsv"))

# ORA, GO-BP
cg.BP = compareCluster(cmpList, fun = "enrichGO", OrgDb = org.Hs.eg.db, ont = "BP",
                       pAdjustMethod = "BH", pvalueCutoff = 0.05, readable = T)
saveRDS(cg.BP, file = here::here("output", DOCNAME, "HSC_lmm_da_time.ORA_GOBP_by_PG.rds"))
as.data.frame(cg.BP) |> 
  write_tsv(here::here("output", DOCNAME, "HSC_lmm_da_time.ORA_GOBP_by_PG.tsv"))
```

### KEGG

```{r, fig.width=7, fig.height=9}
ck <- readRDS(here::here("output", DOCNAME, "HSC_lmm_da_time.ORA_KEGG_by_PG.rds"))

dotplot(ck, showCategory = 10, title = "KEGG")
```

### GO-BP

```{r, fig.width=8, fig.height=8}
cg.BP <- readRDS(here::here("output", DOCNAME, "HSC_lmm_da_time.ORA_GOBP_by_PG.rds"))
s_cg.BP <- simplify(cg.BP, cutoff = 0.5)

dotplot(cg.BP, showCategory = 10, title = "GO:BP") +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60))
dotplot(s_cg.BP, showCategory = 10, title = "GO:BP") +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60))
```

### Save

HSC PG links

```{r}
df_pg <- readRDS(here::here("output", "HSC.lmmPG", "HSC.lmmPG_FDR20.rds")) |> 
  dplyr::select(peak, gene) |> 
  group_by(peak) |> 
  summarise(
    gene = paste(gene, collapse = ","), .groups = "drop"
  )
head(df_pg[,1:2])
```

write

```{r}
df_de_ln |> 
  dplyr::rename(peak = gene) |> 
  left_join(df_pg, by = "peak") |> 
  dplyr::select(peak, beta, LTSR = ltsr, target_genes = gene) |> 
  write_tsv(file = here::here("output", DOCNAME, "HSC_dev_da_peak_and_target_genes.tsv"))
```

## Session info

