---
title: "DE_rna"
---

- Use the results here `/work/DevM_analysis/01.annotation/10.integration_joint_clean/data/FL_wnn_markerGenes.v00.csv`

```{r knitr, include = FALSE}
DOCNAME <- "DE_rna"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Set up

```{r}
library(tidyverse)

# plot
library(scattermore)
library(ggrastr)
library(ComplexHeatmap)

# patch
library(patchwork)
library(cowplot)
theme_set(theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
))
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(ggsci)

# srat
library(Seurat)
```

```{r source, cache = FALSE}
source(here::here("code/preprocess.R"))
source(here::here("code/color.R"))
source(here::here("code/plot.R"))
source(here::here("code/markers.R"))
```

## Load data

```{r}
srat <- readRDS("/work/DevM_analysis/01.annotation/10.integration_joint_clean/data/FL_rna_clustered.v01.rds")
srat
```

Load marker genes

```{r}
markerGenes <- read_csv("/work/DevM_analysis/01.annotation/10.integration_joint_clean/data/FL_wnn_markerGenes.v00.csv")
```

## Prep for heatmaps

```{r}
col_order <- c("HSC", "GP", "Granulocyte",
                                                  "49-MEMP", "MEMP", "MEP", "MEMP-Mast-Ery", "MEMP-Ery", "Early-Ery", "Late-Ery",
                                                  "MEMP-MK", "MK", "49:2-MastP", "MastP", "Mast", "35-MDP?",
                                                  "Monocyte", "Kupffer", "cDC1", "cDC2", "pDC", "ASDC",
                                                  "LMPP", "LP", "Cycling_LP", "PreProB", "ProB-1", "ProB-2",
                                                  "Large-PreB", "Small-PreB", "IM-B",
                                                  "NK", "ILCP", "T",
                                                  "Hepatocyte", "Endothelia")
col_name_new <- c("HSC", "GP", "Granulocyte",
                  "MEMP-t", "MEMP", "MEP", "MEMP-Mast-Ery", "MEMP-Ery", "Early-Ery", "Late-Ery",
                  "MEMP-MK", "MK", "MastP-t", "MastP", "Mast", "MDP",
                  "Monocyte", "Kupffer", "cDC1", "cDC2", "pDC", "ASDC",
                                                  "LMPP", "LP", "Cycling-LP", "PreProB", "ProB-1", "ProB-2",
                                                  "Large-PreB", "Small-PreB", "IM-B",
                                                  "NK", "ILCP", "T",
                                                  "Hepatocyte", "Endothelia")
```

## Top DEGs {.tabset}

### 100

Get top 100 markers

```{r}
topGene = markerGenes %>%
  group_by(group) %>%
  slice_min(n = 100, order_by = pvals_adj, with_ties = FALSE)

DT::datatable(topGene)
```

Plot

```{r , message=FALSE, warning=FALSE, fig.width=5, fig.height=6}
# to list
topGene_lst = split(topGene$names, topGene$group)
topGene_lst <- topGene_lst[col_order]
names(topGene_lst) <- col_name_new

# get exp
Idents(srat)<- "anno_wnn_v51"
mat = AverageExpression(srat, assays = "RNA", features = unique(unlist(topGene_lst, use.names = FALSE)),
                        slot = "data", verbose = F)$RNA
mat = log1p(as.matrix(mat))
# scale
mat_scale = pheatmap:::scale_rows(mat)

# sort within group
sorted_genes <- c()
for (i in 1:length(topGene_lst)) {
  gs <- topGene_lst[[i]]
  gs <- setdiff(gs, sorted_genes)
  gs_v <- mat_scale[gs, i]
  gs_sorted <- names(sort(gs_v, decreasing = T))
  sorted_genes <- c(sorted_genes, gs_sorted)
}
mat_p <- mat_scale[sorted_genes,]

# color
#range(mat_p)
#quantile(mat_p, c(0.05, 0.1, 0.5, 0.8, 0.9, 0.95), na.rm=TRUE)
#        5%        10%        50%        80%        90%        95% 
#-1.0875356 -0.8822238 -0.2424510  0.5534316  1.2901544  1.9253929
col_fun = circlize::colorRamp2(c(-6, 0, 6), c("blue", "white", "red"))

# marker to label
# check which ones to be labeled
#sapply(topGene_lst, function(x){intersect(x, blood_markers_more)})
marker_2_lab = c("MECOM", "SPINK2", "HLF", # HSC
                 "MRC1", # 35-MDP?
                 "MPO", "AZU1", # GP/Granulocyte
                 "GATA2", "TESPA1", # MEMP
                 "TFRC", "FAM178B", "AHSP", # Ery
                 "ITGA2B", "PF4", # MK
                 "HDC", "LMO4", "ENPP3", # Mast
                 "MRC1", # MDP
                 "VCAN", "FCN1", "MNDA", # Mono
                 "STAB1", "CD163", "CTSB", # Kupffer
                 "BATF3", # cDC1
                 "IL3RA", "CLEC4C", # pDC
                 "AXL", # pDC
                 "IL7R", "JCHAIN", # LP
                 "PAX5", "EBF1", "CD79B", "IGHM",  # B
                 "NKG7", "KLRB1", # NK
                 "TCF7", "AHR", # ILC
                 "AFP", # Hepa
                 "STAB2", "KDR", # Endo
                 "MKI67",
                 "RPL34", "RPS28"
                 )
# label location
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(mat_p) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat_p, name = "Exp.",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(at = c(-6, 0, 6),
                                    #direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p

ggsave2(
  filename = here::here("output", DOCNAME, "FL_wnn_markerGenes_top100.heatmap.pdf"),
  width = 5, height = 6
)
```


### 100 ranked by score

Get top 100 markers

```{r}
topGene = markerGenes %>%
  group_by(group) %>%
  slice_max(n = 100, order_by = scores, with_ties = FALSE)

DT::datatable(topGene)
```

Plot

```{r , message=FALSE, warning=FALSE, fig.width=5, fig.height=6}
# to list
topGene_lst = split(topGene$names, topGene$group)
topGene_lst <- topGene_lst[col_order]
names(topGene_lst) <- col_name_new

# get exp
Idents(srat)<- "anno_wnn_v51"
mat = AverageExpression(srat, assays = "RNA", features = unique(unlist(topGene_lst, use.names = FALSE)),
                        slot = "data", verbose = F)$RNA
mat = log1p(as.matrix(mat))
# scale
mat_scale = pheatmap:::scale_rows(mat)

# sort within group
sorted_genes <- c()
for (i in 1:length(topGene_lst)) {
  gs <- topGene_lst[[i]]
  gs <- setdiff(gs, sorted_genes)
  gs_v <- mat_scale[gs,i]
  gs_sorted <- names(sort(gs_v, decreasing = T))
  sorted_genes <- c(sorted_genes, gs_sorted)
}
mat_p <- mat_scale[sorted_genes,]

# color
#range(mat_p)
#quantile(mat_p, c(0.05, 0.1, 0.5, 0.8, 0.9, 0.95), na.rm=TRUE)
#        5%        10%        50%        80%        90%        95% 
#-1.0632260 -0.8687643 -0.2492242  0.5291847  1.2933113  1.9493648
col_fun = circlize::colorRamp2(c(-6, 0, 6), c("blue", "white", "red"))

# marker to label
# check which ones to be labeled
#sapply(topGene_lst, function(x){intersect(x, blood_markers_more)})
marker_2_lab = c("MECOM", "MLLT3", "HLF", # HSC
                 "MPO", "AZU1", # GP/Granulocyte
                 "GATA2", "TESPA1", # MEMP
                 "TFRC", "FAM178B", "AHSP", # Ery
                 "ITGA2B", "PLEK", "PF4", # MK
                 "MRC1", # 35-MDP?
                 "HDC", "LMO4", "ENPP3", # Mast
                 "VCAN", "FCN1", "MNDA", # Mono
                 "STAB1", "CD163", "CTSB", # Kupffer
                 "BATF3", # cDC1
                 "IL3RA", "CLEC4C", # pDC
                 "AXL", # pDC
                 "IL7R", "JCHAIN", # LP
                 "EBF1", "PAX5", "CD79B", "IGHM",  # B
                 "NKG7", "NCAM1", # NK
                 "TCF7", "AHR", # ILC
                 "AFP", # Hepa
                 "STAB2", "KDR", # Endo
                 "MKI67", "RPS2"
                 )
# label location
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(mat_p) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat_p, name = "Exp.",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(at = c(-6, 0, 6),
                                    #direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p

ggsave2(
  filename = here::here("output", DOCNAME, "FL_wnn_markerGenes_top100_byScores.heatmap.pdf"),
  width = 5, height = 6
)
```

### 50

Get top 50 markers

```{r}
topGene = markerGenes %>%
  group_by(group) %>%
  slice_min(n = 50, order_by = pvals_adj, with_ties = FALSE)

DT::datatable(topGene)
```

Plot

```{r , message=FALSE, warning=FALSE, fig.width=5, fig.height=6}
# de-duplicate
#topGene = topGene[!duplicated(topGene$gene),]

# to list
topGene_lst = split(topGene$names, topGene$group)
topGene_lst <- topGene_lst[col_order]
names(topGene_lst) <- col_name_new

# marker
# check which ones to be labeled
#sapply(topGene_lst, function(x){intersect(x, blood_markers_more)})
marker_2_lab = c("MECOM", "PROM1", "CD34", # HSC
                 "MRC1", # 35-MDP?
                 "MPO", "AZU1", # GP/Granulocyte
                 "GATA2", "TESPA1", # MEMP
                 "TFRC", "AHSP", # Ery
                 "ITGA2B", "PLEK", # MK
                 "HDC", "LMO4", # Mast
                 "VCAN", "FCN1", "MNDA", # Mono
                 "STAB1", "CD163", # Kupffer
                 "FLT3", # cDC1
                 "CTSB", # cDC2
                 "IRF8", "IL3RA", # pDC
                 "AXL", # pDC
                 "IL7R", "JCHAIN", # LP
                 "PAX5", "IGLL1", "CD79B", "IGHM",  # B
                 "NKG7", "KLRB1", # NK
                 "KIT", # ILC
                 "ALB", "AFP", # Hepa
                 "STAB2", "KDR" # Endo
                 )

# get exp
Idents(srat)<- "anno_wnn_v51"
mat = AverageExpression(srat, assays = "RNA", features = unique(unlist(topGene_lst)),
                        slot = "data", verbose = F)$RNA
mat = log1p(as.matrix(mat))

# scale
mat_scale = pheatmap:::scale_rows(mat)

# color
#range(mat_scale)
#x = ceiling(max(abs(mat_scale)))
col_fun = circlize::colorRamp2(c(-5, 0, 5), c("blue", "white", "red"))

# label location
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(mat) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat_scale, name = "Exp.",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(#direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p.markers.top = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top

ggsave2(
  filename = here::here("output", DOCNAME, "FL_wnn_markerGenes_top50.heatmap.pdf"),
  width = 5, height = 6
)
```

### Top 10

```{r fig.width=5, fig.height=20}
topGene = markerGenes %>%
  group_by(group) %>%
  slice_min(n = 10, order_by = pvals_adj, with_ties = FALSE)

topGene_lst = split(topGene$names, topGene$group)
topGene_lst <- topGene_lst[col_order]
names(topGene_lst) <- col_name_new

# get exp
Idents(srat)<- "anno_wnn_v51"
mat = AverageExpression(srat, assays = "RNA", features = unique(unlist(topGene_lst)),
                        slot = "data", verbose = F)$RNA
mat = log1p(as.matrix(mat))

# scale
mat_scale = pheatmap:::scale_rows(mat)

ht = Heatmap(mat_scale, name = "Exp.",
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = T,
        row_names_gp = gpar(fontsize = 6),
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(#direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p.markers.top = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top

ggsave2(
  filename = here::here("output", DOCNAME, "FL_wnn_markerGenes_top10.heatmap.pdf"),
  width = 5, height = 20
)
```

### Top 5

```{r fig.width=5, fig.height=12}
topGene = markerGenes %>%
  group_by(group) %>%
  slice_min(n = 5, order_by = pvals_adj, with_ties = FALSE)

topGene_lst = split(topGene$names, topGene$group)
topGene_lst <- topGene_lst[col_order]
names(topGene_lst) <- col_name_new

# get exp
Idents(srat)<- "anno_wnn_v51"
mat = AverageExpression(srat, assays = "RNA", features = unique(unlist(topGene_lst)),
                        slot = "data", verbose = F)$RNA
mat = log1p(as.matrix(mat))

# scale
mat_scale = pheatmap:::scale_rows(mat)

ht = Heatmap(mat_scale, name = "Exp.",
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = T,
        row_names_gp = gpar(fontsize = 6),
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(#direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p.markers.top = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top

ggsave2(
  filename = here::here("output", DOCNAME, "FL_wnn_markerGenes_top5.heatmap.pdf"),
  width = 5, height = 12
)
```

### Given markers

```{r , message=FALSE, warning=FALSE, fig.width=5, fig.height=6, eval=FALSE}
# get exp
Idents(srat)<- "anno_wnn_v5"
mat = AverageExpression(srat, assays = "RNA", features = blood_markers_more,
                        slot = "data", verbose = F)$RNA
mat = log1p(as.matrix(mat))

# scale
mat_scale = pheatmap:::scale_rows(mat)

# color
#range(mat_scale)
#x = ceiling(max(abs(mat_scale)))
col_fun = circlize::colorRamp2(c(-5, 0, 5), c("blue", "white", "red"))

# label location
marker_2_lab = c("SPINK2", "MECOM", "HLF", # HSC
                 "MPO", "AZU1", # GP/Granulocyte
                 "GATA2", "TESPA1", # MEMP
                 "KLF1", "AHSP", # Ery
                 "ITGA2B", "PF4", # MK
                 "HDC", "LMO4", "ENPP3", # Mast
                 "VCAN", "FCN1", "MNDA", # Mono
                 "CD163", "CTSB", # Kupffer
                 "CLEC9A", "BATF3", # cDC1
                 "CD1C", "CLEC4A", # cDC2
                 "IRF8", "CLEC4C", "IL3RA", # pDC
                 "AXL", # pDC
                 "IL7R", "JCHAIN", # LP
                 "PAX5", "IGLL1", "CD79B", "IGHM",  # B
                 "NKG7", "KLRB1", # NK
                 "AHR", "KIT", # ILC
                 "ALB", "AFP", # Hepa
                 "STAB2", "KDR", # Endo
                 'MKI67'
                 )
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(mat) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))

ht = Heatmap(mat_scale, name = "Exp.",
        col = col_fun,
        right_annotation = ha,
        cluster_columns = F,
        cluster_rows = F,
        show_row_names = FALSE,
        column_names_gp = gpar(fontsize = 6),
        #column_names_rot = 60,
        heatmap_legend_param = list(#direction = "horizontal",
                                    labels_gp = gpar(fontsize = 6),
                                    title_gp = gpar(fontsize = 6),
                                    #title_position = "leftcenter",
                                    grid_height = unit(2, "mm"),
                                    grid_width = unit(2, "mm"))
        )
#draw(ht, heatmap_legend_side = "bottom")
p.markers.top = plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top
```

## Session info

