---
title: "archr.de_gs"
---

```{r knitr, include = FALSE}
DOCNAME <- "archr.de_gs"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Set up

```{r}
library(tidyverse)

# plot
library(scattermore)
library(ggrastr)
library(ComplexHeatmap)

# patch
library(patchwork)
library(cowplot)
theme_set(theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
))
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(ggsci)

# srat
library(Seurat)
library(ArchR)
```

```{r source, cache = FALSE}
source(here::here("code/markers.R"))
```

## Set ArchR

```{r set-ArchR, cache=FALSE}
# set up
set.seed(1)
# default number of threads
addArchRThreads(threads = 12)
# add a reference genome annotation for ArchR
addArchRGenome("hg38")
# chr prefix to exclude KI/GL scaffolds
addArchRChrPrefix(chrPrefix = TRUE)
```

## Load data

Load saved proj

```{r load-proj, cache=FALSE}
proj <- loadArchRProject(path = here::here("output", "archr_48FL"))
proj
```

## Prep for heatmaps

```{r}
col_order <- c("HSC", "GP", "Granulocyte",
                                                  "49-MEMP", "MEMP", "MEP", "MEMP-Mast-Ery", "MEMP-Ery", "Early-Ery", "Late-Ery",
                                                  "MEMP-MK", "MK", "49:2-MastP", "MastP", "Mast", "35-MDP",
                                                  "Monocyte", "Kupffer", "cDC1", "cDC2", "pDC", "ASDC",
                                                  "LMPP", "LP", "Cycling_LP", "PreProB", "ProB-1", "ProB-2",
                                                  "Large-PreB", "Small-PreB", "IM-B",
                                                  "NK", "ILCP", "T",
                                                  "Hepatocyte", "Endothelia")
col_name_new <- c("HSC", "GP", "Granulocyte",
                                                  "MEMP-t", "MEMP", "MEP", "MEMP-Mast-Ery", "MEMP-Ery", "Early-Ery", "Late-Ery",
                                                  "MEMP-MK", "MK", "MastP-t", "MastP", "Mast", "MDP",
                                                  "Monocyte", "Kupffer", "cDC1", "cDC2", "pDC", "ASDC",
                                                  "LMPP", "LP", "Cycling-LP", "PreProB", "ProB-1", "ProB-2",
                                                  "Large-PreB", "Small-PreB", "IM-B",
                                                  "NK", "ILCP", "T",
                                                  "Hepatocyte", "Endothelia")
```

## Top marker genes

```{r}
markersGS <- readRDS(here::here("output", "archr_48FL", "MarkerFeatures", "markersGS.rds"))
# adjust order
markersGS <- markersGS[, col_order]

markerGenes <- c(
  "HLF", # HSC
  "MPO", # GMP
  "GATA1", # MEMP
  "HBA1", "AHSP", "ALAS2", "GYPA", # Ery
  "PPBP", "PF4", # MK
  "TPSAB1", # Mast
  "VCAN", "MNDA", "S100A9", # Mono
  "CD163", "C1QA", # Kupffer
  "MRC1", "MPEG1", # Mac-pDC
  "CLEC4C", # pDC_prog, pDC
  "CLEC9A", # cDC1
  "IL7R", # LP
  "CD79A", "MS4A1", "PAX5", "CD24", # B
  "NKG7", "KLRB1", "GZMA", # NK
  "RORC", # ILC
  "CD3E", "CD2", # Early-L/TL
  "AFP", # Hepa
  "COL3A1", "DCN", # Fib
  "CDH5", "KDR" # Endo
)

heatmapGS <- plotMarkerHeatmap(
  seMarker = markersGS,
  cutOff = "FDR <= 0.01 & Log2FC >= 1",
  labelMarkers = markerGenes,
  transpose = TRUE
)
```

The order of genes is not good

```{r fig.width=10, fig.height=8}
ComplexHeatmap::draw(heatmapGS, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```

Return a matrix, plot using complexheatmap

```{r , fig.width=5, fig.height=6}
topMarkers <- getMarkers(markersGS, cutOff = "FDR <= 0.01 & Log2FC >= 1")
top_lst <- lapply(topMarkers, function(i) {
  as.data.frame(i) |>
    pull(name)
})

# get a mat
heatmapGS_mat <- plotMarkerHeatmap(
  seMarker = markersGS,
  cutOff = "FDR <= 0.01 & Log2FC >= 1",
  returnMatrix = TRUE,
  limits = c(-6, 6),
)
colnames(heatmapGS_mat) <- col_name_new

# sort within group
sorted_genes <- c()
for (i in 1:length(top_lst)) {
  gs <- top_lst[[i]]
  gs <- setdiff(gs, sorted_genes)
  gs_v <- heatmapGS_mat[gs,i]
  gs_sorted <- names(sort(gs_v, decreasing = T))
  sorted_genes <- c(sorted_genes, gs_sorted)
}
mat_p <- heatmapGS_mat[sorted_genes,]

# color
#range(mat_p)
#quantile(mat_p, c(0.05, 0.1, 0.5, 0.8, 0.9, 0.95), na.rm=TRUE)
x <- ceiling(max(abs(mat_p)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker to label
# lapply(top_lst, function(x){intersect(x, blood_markers_more)})
marker_2_lab <- c(
  "HLF", # HSC
  "MRC1", # 35-MDP
  "MPO", "AZU1", # GMP
  "GATA1", # MEMP
  "FAM178B", "TFRC", # Ery
  "PF4", "ITGA2B", # MK
  "TPSAB1", "CPA3", # Mast
  "VCAN", "XCR1", # Mono
  "CD163", "CTSB", # Kupffer
  "IRF8", "MS4A7", "MPEG1", # cDC
  "IL7R", "JCHAIN", # LP
  "CD79B", "MS4A1", "PAX5", "EBF1", # B
  "IL2RB", "NKG7", # NK
  "RORC", "TCF7", # ILC
  "CD3D", "CD3G",
  "ALB", 
  "KDR", "CDH5"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat_p) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_p,
  name = "z-score",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = FALSE,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list(
    at = c(-6, 0, 6),
    # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)

# draw(ht, heatmap_legend_side = "bottom")
p.markers <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers
```

## Top 100

```{r , fig.width=5, fig.height=6}
top_lst <- lapply(topMarkers, function(i) {
  as.data.frame(i) |>
    pull(name) %>% 
    head(100)
})

# sort within group
sorted_genes <- c()
for (i in 1:length(top_lst)) {
  gs <- top_lst[[i]]
  gs <- setdiff(gs, sorted_genes)
  gs_v <- heatmapGS_mat[gs,i]
  gs_sorted <- names(sort(gs_v, decreasing = T))
  sorted_genes <- c(sorted_genes, gs_sorted)
}
mat_p <- heatmapGS_mat[sorted_genes,]

# color
#range(mat_p)
#quantile(mat_p, c(0.05, 0.1, 0.5, 0.8, 0.9, 0.95), na.rm=TRUE)
# color
x <- ceiling(max(abs(mat_p)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker to label
# lapply(top_lst, function(x){intersect(x, blood_markers_more)})
marker_2_lab <- c(
  "HLF", # HSC
  "MRC1", # 35-MDP
  "MPO", "AZU1", # GMP
  "GATA1", # MEMP
  "FAM178B", "TFRC", # Ery
  "PF4", "ITGA2B", # MK
  "TPSAB1", "CPA3", # Mast
  "VCAN", "XCR1", # Mono
  "CD163", "CTSB", # Kupffer
  "IRF8", "MS4A7", "MPEG1", # cDC
  "IL7R", "JCHAIN", # LP
  "CD79B", "MS4A1", "PAX5", "EBF1", # B
  "IL2RB", "NKG7", # NK
  "RORC", "TCF7", # ILC
  "CD3D", "CD3G",
  "ALB", 
  "KDR", "CDH5"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat_p) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_p,
  name = "z-score",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = FALSE,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list(
    at = c(-6, 0, 6),
    # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)

# draw(ht, heatmap_legend_side = "bottom")
p.markers.top100 <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top100

ggsave2(
  filename = here::here("output", DOCNAME, "ArchR_markerGS_top100.heatmap.pdf"),
  width = 5, height = 6
)
```

## Session info
