---
title: "variancePartition.composition"
---

```{r knitr, include = FALSE}
DOCNAME <- "variancePartition.composition"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

```{r}
library(tidyverse)
library(data.table)

# plot
library(scales)
library(scattermore)
library(ggrastr)
library(ggpubr)

# patch
library(patchwork)
library(cowplot)
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(ggsci)

# srat
library(Seurat)

# model
library(variancePartition)
```

```{r source, cache = FALSE}
#source(here::here("utils/preprocess.R"))
#source(here::here("utils/markers.R"))
#source(here::here("utils/color.R"))
source(here::here("utils/plot.R"))
theme_set(publ_theme)
source(here::here("utils/CellTypeCompositionAnalysis.R"))
```

## Set up

Load cellmeta

```{r}
srat <- readRDS("/work/DevM_analysis/02.abundance/Milo_FL_PCW250401/data/FL_rna_clustered.rds")
srat
```

Neat

```{r}
obs_tbl <- srat@meta.data |>
  rownames_to_column("barcode")

obs_tbl$PCWsca <- as.numeric(scale(as.integer(as.character(obs_tbl$PCW))))
unique(obs_tbl$PCWsca)
```

count table (cell number of each cell type and each sample)

```{r}
Y <- .make_count_matrix(obs_tbl, "sampleID", "anno_wnn_v51")
dim(Y)
```

Pearson's Contingency Coefficient (ref: <https://www.nature.com/articles/s41591-024-03215-z>)

```{r}
chi_res <- chisq.test(Y)
C <- sqrt(chi_res$statistic / (chi_res$statistic + sum(Y)))
cat(C)

expected_counts <- chi_res$expected
normalized <- Y / expected_counts
log_norm <- t(log1p(normalized))
class(log_norm) <- "matrix"
```

meta data

```{r}
metadata <- obs_tbl |> 
  dplyr::select(sampleID, libraryID, donorID, Sex, PCWsca, Batch) |> 
  distinct() |> 
  mutate(Sex = factor(Sex, levels = c("M", "F")),
         donorID = factor(donorID)) |> 
  mutate(Batch = factor(Batch))

metadata <- metadata |> 
  column_to_rownames("sampleID")
metadata <- metadata[colnames(log_norm),]
str(metadata)
```

## Raw count

```{r fig.width=6, fig.height=8}
form <- ~ PCWsca + (1 | libraryID) + (1 | donorID) + (1 | Sex) + (1 | Batch)

# raw count
mat <- t(Y)
class(mat) <- "matrix"

# Fit model and extract results
varPart <- fitExtractVarPartModel(mat, form, metadata)
# sort variables (i.e. columns) by median fraction of variance explained
vp <- sortCols(varPart)
# Bar plot of variance fractions for the first 10 genes
plotPercentBars(vp) +
  scale_fill_jco()
```

```{r fig.width=5, fig.height=4}
# violin plot of contribution of each variable to total variance
plotVarPart(vp) +
  publ_theme +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

## Pearson's Contingency Coefficient

```{r fig.width=6, fig.height=8}
form <- ~ PCWsca + (1 | libraryID) + (1 | donorID) + (1 | Sex) + (1 | Batch)

# Fit model and extract results
varPart <- fitExtractVarPartModel(log_norm, form, metadata)
# sort variables (i.e. columns) by median fraction of variance explained
vp <- sortCols(varPart)
# Bar plot of variance fractions for the first 10 genes
plotPercentBars(vp) +
  scale_fill_jco()

ggsave2(
  filename = here::here("output", DOCNAME, "varPartComposition.variance_of_each_variable.pdf"),
  width = 6, height = 8
)
```

```{r fig.width=5, fig.height=4}
# violin plot of contribution of each variable to total variance
plotVarPart(vp) +
  publ_theme +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

ggsave2(
  filename = here::here("output", DOCNAME, "varPartComposition.covariate_contribution.pdf"),
  width = 5, height = 4
)
```

Save

```{r}
saveRDS(varPart, file = here::here("output", DOCNAME, "PBvarPart.rds"))
saveRDS(vp, file = here::here("output", DOCNAME, "PBvp.rds"))
```

## Session info
