---
title: "archr.HSC_CvsQ.chromVAR_ChIP_peak"
author: "Yiwei Niu"
---

```{r knitr, include = FALSE}
DOCNAME <- "archr.HSC_CvsQ.chromVAR_ChIP_peak"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Set up

```{r}
library(tidyverse)
library(glue)

# plot
library(scattermore)
library(ggrastr)
library(ComplexHeatmap)

# patch
library(patchwork)
library(cowplot)
theme_set(theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
))
mytheme <- theme_cowplot(
  font_size = 10,
  rel_small = 8 / 10,
  rel_tiny = 8 / 10,
  rel_large = 10 / 10
)

# color
library(ggsci)

# srat
library(Seurat)
library(ArchR)
```

```{r source, cache = FALSE}
source("/work/home/project/20231127_DevM/devm_r432/utils/plot.R")
print(1)
range01 <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}
```

## Set ArchR

```{r set-ArchR, cache=FALSE}
# set up
set.seed(1)
# default number of threads
addArchRThreads(threads = 12)
# add a reference genome annotation for ArchR
addArchRGenome("hg38")
# chr prefix to exclude KI/GL scaffolds
addArchRChrPrefix(chrPrefix = TRUE)
```

## Load data

Load saved proj

```{r load-proj, cache=FALSE}
data_dir <- "archr_48FL.eachCell"
cell <- "HSC"

# load
proj_dir <- here::here('output', data_dir, cell)
proj <- loadArchRProject(path = proj_dir)
proj
getAvailableMatrices(proj)
```

```{r}
# add qHSC/cHSC labels
df <- read_csv("/work/DevM_analysis/05.cellcycle/data/HSC_CCPhase_VCTime.csv") %>%
  mutate(barcode = str_replace(barcode, '_', '#'),
         Phase_CvsQ = case_when(
           CC_Phase == "G0" ~ "G0",
           TRUE ~ "non-G0"
         )) %>%
  column_to_rownames("barcode")
df <- df[proj$cellNames,]
proj$Phase_CvsQ <- df$Phase_CvsQ
proj$CC_Phase <- df$CC_Phase
```

function

```{r}
.plot_z_by_tf <- function(archr_proj = NULL, celltype = NULL, TF = NULL) {
  cell <- celltype
  tf <- TF
  
  p <- plotGroups(
    ArchRProj = archr_proj,
    groupBy = "Phase_CvsQ",
    colorBy = "HSPC_ChIPMatrix",
    name = glue("z:{cell}_{tf}"),
    imputeWeights = NULL,
    maxCells = 1000000
  )
  
  cellmeta <- getCellColData(archr_proj) %>%
    as.data.frame() %>%
    rownames_to_column("barcode") %>%
    dplyr::select(barcode, CC_Phase, Phase_CvsQ) %>% 
    mutate(
      Phase_CvsQ = factor(Phase_CvsQ, levels = c("G0", "non-G0")),
      CC_Phase = factor(CC_Phase, levels = c("G0", "G1", "S", "G2M"))
    )
  
  dat <- p$data %>%
    rownames_to_column("barcode") %>%
    dplyr::select(barcode, value = y)
  
  df <- dat %>%
    left_join(cellmeta, by = "barcode") %>% 
    droplevels()
  
  p1 <- df %>% 
    ggplot(aes(x = Phase_CvsQ, y = value)) +
    ggrastr::rasterize(geom_boxplot(outlier.size = 0.1,
               outlier.alpha = 0.3,
               outlier.color = NULL,
               fatten = 1), dpi = 300) +
    labs(x = NULL, y = glue("ChromVAR z")) +
    publ_theme +
    theme(axis.text.x = element_text(angle = 60, hjust = 1))
  p2 <- df %>% 
    ggplot(aes(x = CC_Phase, y = value)) +
    ggrastr::rasterize(geom_boxplot(outlier.size = 0.1,
               outlier.alpha = 0.3,
               outlier.color = NULL,
               fatten = 1), dpi = 300) +
    labs(x = NULL, y = glue("ChromVAR z")) +
    publ_theme +
    theme(axis.text.x = element_text(angle = 60, hjust = 1))
  if (tf == "PU1") {
    tf = "PU.1"
  }
  p <- p1 + p2 +
    plot_layout(ncol = 2, widths = c(1, 1.8)) +
    plot_annotation(title = glue("{cell}-{tf}"),
                    theme = theme(plot.title = element_text(size = 10)))
  return(plot_grid(p))
}
```

## Test {.tabset}

The deviations

```{r fig.width=3, fig.height=3}
cell <- "MEP"
tf <- "CTCF"

p <- plotGroups(
  ArchRProj = proj,
  groupBy = "Phase_CvsQ",
  colorBy = "HSPC_ChIPMatrix",
  name = glue("deviations:{cell}_{tf}"),
  imputeWeights = NULL,
  maxCells = 1000000
)

cellmeta <- getCellColData(proj) %>%
  as.data.frame() %>%
  rownames_to_column("barcode") %>%
  dplyr::select(barcode, CC_Phase, Phase_CvsQ)

dat <- p$data %>%
  rownames_to_column("barcode") %>%
  dplyr::select(barcode, value = y)

df <- dat %>%
  left_join(cellmeta, by = "barcode") %>% 
  droplevels()

p1 <- df %>% 
  ggplot(aes(x = reorder(Phase_CvsQ, value, median), y = value)) +
  geom_boxplot() +
  labs(x = NULL, y = glue("ChromVAR deviations")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p2 <- df %>% 
  ggplot(aes(x = reorder(CC_Phase, value, median), y = value)) +
  geom_boxplot() +
  labs(x = NULL, y = glue("ChromVAR deviations")) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
p1 + p2 +
  plot_layout(ncol = 2, widths = c(1, 1.8)) +
  plot_annotation(title = glue("{cell}-{tf}"))
```

z-score

```{r fig.width=2, fig.height=2}
.plot_z_by_tf(archr_proj = proj, celltype = "MEP", TF = "CTCF")
```

## MEP {.tabset}

```{r fig.width=8, fig.height=6}
TFs <- c("CTCF", "STAG2", "ERG", "FLI1", "GATA2", "LMO2", "LYL1", "PU1", "RUNX1", "TAL1")
p_lst <- lapply(TFs, function(x){
  .plot_z_by_tf(archr_proj = proj, celltype = "MEP", TF = x)
})

p <- p_lst %>% 
  wrap_plots(ncol = 4)
p

ggsave2(
  filename = here::here("output", DOCNAME, "HSC_CvsQ.MEP_ChIP_peak.chromVAR_boxplot.pdf"),
  width = 8, height = 6
)
```

## GMP {.tabset}

```{r fig.width=8, fig.height=6}
p_lst <- lapply(TFs, function(x){
  .plot_z_by_tf(archr_proj = proj, celltype = "GMP", TF = x)
})

p <- p_lst %>% 
  wrap_plots(ncol = 4)
p

ggsave2(
  filename = here::here("output", DOCNAME, "HSC_CvsQ.GMP_ChIP_peak.chromVAR_boxplot.pdf"),
  width = 8, height = 6
)
```

## Session info
